### ISSUE TITLE
No location exists. Check if GPS enabled

### ISSUE THREAD

**Issue by eddydn** [Skullper/SimpleLocationGetter#1]
I get this error !

**Comment by Skullper** [comment]
@eddydn Or your GPS not enabled, or you haven't GPS on your device, or GoogleClient cannot retrieve your current location

**Comment by eddydn** [comment]
I'm using Android Emulator for Test , i've enable FINE LOCATION and COARSE LOCATION , INTERNET permission but still get this error

**Comment by Skullper** [comment]
@eddydn Have you enabled GPS on your emulator?
