### ISSUE TITLE
Override Manifest  error

### ISSUE THREAD

**Issue by vijayakumarksv** [Skullper/SimpleLocationGetter#4]
Hi,
    I have added library in gradle after that i got this error message 
    implementation 'com.google.android.gms:play-services-location:11.0.1'
 
Error:
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:16:5-201:19 to override.

**Comment by Skullper** [comment]
Hi, vijayakumarksv!

Have you tried a suggestion from error trace?

**Comment by vijayakumarksv** [comment]
I found and fixed that issue
